spring:
  application:
    name: eureka

server:
  port: 8761

eureka:
  instance:
    hostname: localhost
#    instance-id: eureka
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: false
    register-with-eureka: false