spring:
  application:
    name: nacos-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 106.53.227.249:8848
    sentinel:
      transport:
        dashboard: 106.53.227.249:8991

server:
  port: 8084

feign:
  hystrix:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
